import {serve,ORIGIN} from '../demo.mjs';
import {mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
const screenshotDir=resolve(process.env.HOUSEKI_SCREENSHOT_DIR??'test-output');await mkdir(screenshotDir,{recursive:true});
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';

const url=ORIGIN;const browser=await chromium.launch();
try{
 const page=await browser.newPage({viewport:{width:1024,height:900}});await serve(page);const errors=[];page.on('pageerror',error=>errors.push(String(error)));page.on('requestfailed',request=>errors.push(request.url()));
 for(const [path,game] of [['index.html','falling-triplets'],['chains.html','colour-chains'],['tools.html','gem-swap'],['tools.html','stone-collapse'],['blocks.html','magnetic-blocks']]){
  await page.goto(`${url}/${path}`);if(path==='tools.html')await page.locator('#game').selectOption(game);await page.locator('.game-screen .gem:not(.ghost)').first().waitFor();assert.equal(await page.locator('#theme').count(),0);assert.equal(await page.locator('button[data-cloth]').count(),5);assert.equal(await page.locator('#pieces').count(),1);
  for(const colour of ['green','blue','red','black','wood']){await page.locator(`button[data-cloth="${colour}"]`).click();assert.equal(await page.locator('html').getAttribute('data-cloth'),colour);assert.equal(await page.locator(`button[data-cloth="${colour}"]`).getAttribute('aria-checked'),'true');}
  const board=page.locator('#well,#grid'),before=await board.boundingBox();await page.locator('#pieces').selectOption('flat');assert.equal(await page.locator('html').getAttribute('data-pieces'),'flat');const after=await board.boundingBox();assert.equal(before.width,after.width);assert.equal(before.height,after.height);
  for(const width of [360,390,828,1024,1280]){await page.setViewportSize({width,height:900});await page.locator('[data-lang="en"]').click();const english=await board.boundingBox();const enDebug=await page.evaluate(()=>({scrollY:window.scrollY,header:document.querySelector('header').getBoundingClientRect().height,nav:document.querySelector('nav').getBoundingClientRect().height,intro:document.querySelector('.intro').getBoundingClientRect().height,panel:document.querySelector('.panel-head').getBoundingClientRect().height,screen:document.querySelector('.game-screen').getBoundingClientRect().toJSON(),children:[...document.querySelector('.game-screen').children].map(element=>({tag:element.tagName,id:element.id,cls:element.className,y:element.getBoundingClientRect().y,h:element.getBoundingClientRect().height}))}));await page.locator('[data-lang="ja"]').click();const japanese=await board.boundingBox();const jaDebug=await page.evaluate(()=>({scrollY:window.scrollY,header:document.querySelector('header').getBoundingClientRect().height,nav:document.querySelector('nav').getBoundingClientRect().height,intro:document.querySelector('.intro').getBoundingClientRect().height,panel:document.querySelector('.panel-head').getBoundingClientRect().height,screen:document.querySelector('.game-screen').getBoundingClientRect().toJSON(),children:[...document.querySelector('.game-screen').children].map(element=>({tag:element.tagName,id:element.id,cls:element.className,y:element.getBoundingClientRect().y,h:element.getBoundingClientRect().height}))}));assert.ok(Math.abs(english.x-japanese.x)<=1&&Math.abs(english.y-japanese.y)<=1&&english.width===japanese.width&&english.height===japanese.height,`${game}: language must preserve board position and dimensions ${JSON.stringify({english,japanese,enDebug,jaDebug})}`);}await page.setViewportSize({width:1024,height:900});await page.locator('[data-lang="en"]').click();await page.reload();assert.equal(await page.locator('html').getAttribute('data-cloth'),'wood');assert.equal(await page.locator('#pieces').inputValue(),'flat');await page.locator('#pieces').selectOption('glossy');
 }
 await page.goto(`${url}/api.html`);assert.equal(await page.locator('head link[rel="icon"]').count(),1);assert.ok((await page.locator('head link[rel="icon"]').getAttribute('href')).startsWith('data:image/svg+xml,'));assert.ok((await page.locator('body').innerText()).trimStart().startsWith('Houseki'));assert.equal(await page.locator('button[data-cloth="wood"]').getAttribute('aria-checked'),'true');const text=await page.locator('body').innerText();for(const wrong of ['/colourChains"','/fallingTriplets"','/gemSwap"','/stoneCollapse"','/magneticBlocks"'])assert.equal(text.includes(wrong),false);assert.deepEqual(errors,[]);await page.screenshot({path:resolve(screenshotDir,'houseki-api-reviewed.png'),fullPage:false});console.log('PASS shared family colours, piece appearance, locale-stable board geometry, persistence and clean API rendering');
}finally{await browser.close();}
