import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import * as triplets from '../../dist/falling-triplets.js';
import * as chains from '../../dist/colour-chains.js';
import * as blocks from '../../dist/magnetic-blocks.js';
import * as swap from '../../dist/gem-swap.js';
import * as collapse from '../../dist/stone-collapse.js';
const terminal=state=>['won','lost','finished'].includes(state.phase);
function dropped(engine){let state=engine.createGame({mode:'relaxed',seed:'ending-review'});for(let i=0;i<200&&!terminal(state);i++){const result=engine.applyAction(state,{kind:engine===blocks?'land':'place'});assert.equal(result.accepted,true);state=engine.advanceTicks(result.state,240).state;}assert.equal(state.phase,'lost');return state;}
function firstWin(engine){let state=engine.createLevel(1);for(const step of engine.levelManifest[0].witness){const x=state.active.x??state.active.pivot.x,goal=step.x??step.pivotX;for(let i=0;i<Math.abs(goal-x);i++)state=engine.applyAction(state,{kind:goal<x?'left':'right'}).state;const turns=typeof step.orientation==='number'?step.orientation:({up:0,right:1,down:2,left:3}[step.orientation]);for(let i=0;i<turns;i++)state=engine.applyAction(state,{kind:engine===chains?'rotate-clockwise':'cycle-forward'}).state;state=engine.advanceTicks(engine.applyAction(state,{kind:'hard-drop'}).state,240).state;}assert.equal(state.phase,'won');return state;}
let swapLost=swap.createGame(swap.GEM_SWAP_CAMPAIGN.at(-1).options);while(!terminal(swapLost)){const action=swap.legalActions(swapLost).find(action=>action.kind==='swap');assert.ok(action);swapLost=swap.advanceTicks(swap.applyAction(swapLost,action).state,3600).state;}assert.equal(swapLost.outcome,'lost');
let collapseWon=collapse.createLevel(1);for(const ids of collapse.levelManifest[0].witness){collapseWon=collapse.applyAction(collapseWon,{kind:'select',stoneId:ids[0]}).state;collapseWon=collapse.advanceTicks(collapse.applyAction(collapseWon,{kind:'confirm'}).state,240).state;}assert.equal(collapseWon.phase,'won');
let swapWon=swap.createGame(swap.GEM_SWAP_CAMPAIGN[0].options);for(const operation of swap.GEM_SWAP_CAMPAIGN[0].witness)swapWon=operation.kind==='action'?swap.applyAction(swapWon,operation.action).state:swap.advanceTicks(swapWon,operation.count).state;assert.equal(swapWon.outcome,'won');
const fixtures=[['index.html',triplets,dropped(triplets)],['chains.html',chains,dropped(chains)],['blocks.html',blocks,dropped(blocks)],['tools.html',swap,swapLost],['tools.html',collapse,collapseWon],['tools.html',swap,swapWon],['index.html',triplets,firstWin(triplets)],['chains.html',chains,firstWin(chains)]];
const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'0',BASE_PATH:'/houseki'},stdio:['ignore','pipe','pipe']});
const url=await new Promise((resolve,reject)=>{server.stdout.on('data',data=>{const found=String(data).match(/http:\/\/127\.0\.0\.1:\d+\/houseki/);if(found)resolve(found[0]);});server.on('error',reject);server.on('exit',code=>reject(new Error(`Server exited ${code}`)));});
const browser=await chromium.launch();
try{for(const viewport of [{width:1280,height:900},{width:390,height:844}])for(const [path,engine,state] of fixtures){const page=await browser.newPage({viewport});const errors=[];page.on('pageerror',error=>errors.push(String(error)));const encoded=engine.encodeGame(state);await page.addInitScript(({key,encoded,game})=>{localStorage.setItem(key,encoded);if(game==='gem-swap'||game==='stone-collapse')localStorage.setItem('houseki-full-board-game',game);},{key:`houseki-${state.game}-save`,encoded,game:state.game});await page.goto(`${url}/${path}`);await page.locator('.ending-card').waitFor();const won=state.phase==='won'||state.outcome==='won';assert.match(await page.locator('#ending-title').textContent(),won?/Level complete/:/Game over/);assert.ok((await page.locator('#ending-score').textContent()).includes(String(state.score)));assert.equal(await page.locator('.ending-card').evaluate(card=>document.activeElement===card),true);assert.equal(await page.locator('.controls [data-action]:not([hidden])').evaluateAll(buttons=>buttons.every(button=>button.disabled)),true);if(path==='tools.html')assert.equal(await page.locator('#grid .full-cell').evaluateAll(buttons=>buttons.every(button=>button.disabled)),true);if(won){await page.locator('.ending-next').click();assert.equal(await page.locator('#level').evaluate(select=>select.selectedIndex),2);await page.waitForFunction(()=>document.querySelector('#well')?.dataset.phase==='falling'||document.querySelector('#grid')?.dataset.phase==='ready');}else{await page.locator('.ending-view').click();assert.equal(await page.locator('.ending-badge').isVisible(),true);await page.locator('#restart').click();await page.waitForFunction(()=>!document.querySelector('.ending-layer')||document.querySelector('.ending-layer').hidden);}assert.deepEqual(errors,[]);await page.close();}console.log('PASS win/loss result panels, focus, disabled controls, next level, board review and restart across all five players on desktop/phone');}finally{await browser.close();server.kill();}
