const snapshots=new Map();
const ids=['mode','preset','colours','shape','tools','advanced','code','nature','weather'];
const field=id=>document.getElementById(id);
const value=element=>element.type==='checkbox'?element.checked:element.value;
function assign(element,next){if(element.type==='checkbox')element.checked=Boolean(next);else element.value=String(next);}
export function readFreeSettings(){return Object.fromEntries(ids.filter(id=>field(id)).map(id=>[id,snapshots.get(id)?.value??value(field(id))]));}
export function restoreFreeSettings(values){if(!values||typeof values!=='object'||Array.isArray(values))return;for(const id of ids){const element=field(id),next=values[id];if(!element||next===undefined)continue;if(element.type==='checkbox'){if(typeof next!=='boolean')continue;}else if(typeof next!=='string'||next.length>200||['authored','challenge'].includes(next)||element.tagName==='SELECT'&&![...element.options].some(option=>option.value===next))continue;if(snapshots.has(id))snapshots.get(id).value=next;else assign(element,next);}}
export function syncAuthoredSettings(config,lang='en'){
 if(!config){for(const [id,previous] of snapshots){const element=field(id);if(!element)continue;if(id!=='mode'||element.value===previous.lockedMode)assign(element,previous.value);element.disabled=previous.disabled;delete element.dataset.authoredLock;element.querySelectorAll('option[data-authored]').forEach(option=>option.remove());}snapshots.clear();document.getElementById('fixed-settings-note')?.remove();return;}
 const daily=config.mode==='daily';const desired={mode:daily?'daily':'challenge',preset:'authored',colours:String(config.colourCount),shape:config.shape??'',tools:config.tools??false,advanced:config.advancedTools??false,code:String(config.seed??''),nature:config.nature??false,weather:config.weather??''};
 for(const id of ids){const element=field(id);if(!element)continue;if(!snapshots.has(id))snapshots.set(id,{value:value(element),disabled:element.disabled});snapshots.get(id).lockedMode=desired.mode;element.dataset.authoredLock='true';if(element.tagName==='SELECT'&&![...element.options].some(option=>option.value===String(desired[id]))){const option=document.createElement('option');option.value=String(desired[id]);option.dataset.authored='true';element.append(option);}const option=element.querySelector('option[data-authored]');if(option)option.textContent=id==='preset'?`${daily?(lang==='ja'?'今日':'Daily'):(lang==='ja'?'固定':'Fixed')} · ${config.width} × ${config.height}`:id==='mode'?(lang==='ja'?'チャレンジ':'Challenge'):`${config.colourCount} ${lang==='ja'?'色':'colours'}`;assign(element,desired[id]);element.disabled=id!=='mode';}
 let note=document.getElementById('fixed-settings-note');if(!note){note=document.createElement('p');note.id='fixed-settings-note';note.className='micro';field('preset')?.closest('label')?.after(note);}const option=field('lesson')?.value?field('lesson').selectedOptions[0]:field('level')?.value?field('level').selectedOptions[0]:null;const heading=option?option.textContent+' — ':'';note.textContent=heading+(daily?(lang==='ja'?'今日のパズルの盤面とルールは固定です。':'Daily uses a fixed board and rules.') :lang==='ja'?'このパズルの盤面とルールは固定です。変更するには自由に遊ぶを選んでください。':'This puzzle has a fixed board and rules. Choose Free play to change them.');
}
